
services:
  laravel-app:
    build:
      context: .  # Build dari root (di sini ada composer.json, dll)
      dockerfile: Dockerfile
      target: production
    container_name: laravel-app
    restart: unless-stopped
    volumes:
      - ./storage:/var/www/html/storage:rw
      - ./bootstrap/cache:/var/www/html/bootstrap/cache:rw
      # Mount public folder ke shared volume
      - laravel-public:/var/www/html/public
      # Mount .env file jika perlu
      - ./.env:/var/www/html/.env:ro
    networks:
      - proxy-net
    environment:
      APP_ENV: production
      APP_KEY: base64:0l48qnFS4cpYwJaJsoIyHot/YpR7WgC9fmG/JKzncfc=
      APP_DEBUG: true
      APP_URL: http://154.19.37.110:8000  # Sesuaikan dengan domain
      JAVA_BACKEND_URL: http://154.19.37.110:8080
    healthcheck:
      test: [ "CMD", "php-fpm", "-t" ]
      interval: 30s
      timeout: 10s
      retries: 3

  laravel-nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    restart: unless-stopped
    ports:
      - "8000:80"  # EXPOSE PORT - akses via localhost:8000
    volumes:
      # PERBAIKAN: Share volume public dari laravel-app
      - laravel-public:/var/www/html/public:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - laravel-app
    networks:
      - proxy-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy-net"
      # HTTP di port 8000 (untuk direct access)
      - "traefik.http.routers.laravel-direct.rule=Host(`154.19.37.110`) && Port(`8000`)"
      - "traefik.http.routers.laravel-direct.entrypoints=web8000"
      - "traefik.http.services.laravel-direct.loadbalancer.server.port=80"

      # HTTPS (untuk nanti jika sudah ada domain/SSL)
      - "traefik.http.routers.laravel.rule=Host(`laravel.yourdomain.com`)"  # Ganti nanti
      - "traefik.http.routers.laravel.entrypoints=websecure"
      - "traefik.http.routers.laravel.tls=true"
      - "traefik.http.routers.laravel.tls.certresolver=letsencrypt"
      - "traefik.http.services.laravel.loadbalancer.server.port=80"

      # HTTP to HTTPS redirect (untuk domain nanti)
      - "traefik.http.routers.laravel-insecure.rule=Host(`laravel.yourdomain.com`)"
      - "traefik.http.routers.laravel-insecure.entrypoints=web"
      - "traefik.http.routers.laravel-insecure.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"

volumes:
  laravel-public:
    driver: local

networks:
  proxy-net:
    # PERBAIKAN: Buat network jika belum ada, jangan paksa external
    name: proxy-net
    driver: bridge
    # Atau gunakan external: true jika network sudah ada dari Traefik
